### ISSUE TITLE
BioWin2 Unknown parameters

### ISSUE THREAD

**Issue by sessl3r** [sarabanjina/mycomfortclient#1]
Hi there,
I see you are working also with a Windhager device.
I fight the same device. [My Skripts](https://github.com/sessl3r/windhager)

Hope you read german :)

One question here: As you can see in the README of my repo I have several "Unbekannte Parameter" and for now got no solution for this. Is this something you see as well and eventually already found informations for or even got some from the support?

Regards,
sessl3r

**Comment by DAMEK86** [comment]
Hey,
I'm living near Ulm and yes. I fight the same and speak German too.

I believe this unknown parameters are reserved for other burner types.

Do you have a behavior like burner starts and modulates for around 5 minutes, goes down and requests pellets? This is really annoying.. if you like we can also have a sync over email, teams or so on.

I'm happy to share my knowledge and lern from others to optimze my system :)

**Comment by sessl3r** [comment]
Cool. The world is so small. Me too near Weißenhorn. Please contact me at sessl3r@gmail.com
